druglord/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^/$', main.views.)
]

main/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.home, name='homepage'),
    url(r'^char/(?P<char_id>\d+)/(?P<day_number>\d+)/$', views.day, name='game-day')
]

main/models.py
from django.db import models

# Create your models here.


class Character(models.Model):
    name = models.CharField(max_length=20)
    cash = models.DecimalField(default=50000, max_digits=19, decimal_places=2)
    danger = models.IntegerField(default=0)

    on_day = models.OneToOneField(to='Day', on_delete=models.CASCADE)

    def __str__(self):
        return "Name: {}-{}".format(self.name, self.id)


class Day(models.Model):
    day_number = models.IntegerField()
    day_passed = models.BooleanField(default=False)

    def __str__(self):
        return "Day: {}".format(self.day_number)


class Product(models.Model):
    name = models.CharField(max_length=20)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    danger = models.IntegerField(default=0)

    for_sale = models.ForeignKey(to='Day', on_delete=models.CASCADE)

    def __str__(self):
        return "Product: {}".format(self.name)

main/views.py
import logging

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from . import game_helpers, models

logger = logging.getLogger(__name__)


# Create your views here.


def home(request):
    chars = models.Character.objects.all()

    context = {'characters': chars}

    return render(request, 'main/home.html', context=context)


def day(request, char_id, day_number):
    try:
        day_number = int(day_number)
    except ValueError as e:
        logger.error("Error with day_number: {}".format(e))

    char = get_object_or_404(models.Character, pk=char_id)

    day = game_helpers.create_game_day(day_number)

    context = {
        "char": char,
        "day": day,
        "next_day": day.day_number + 1
    }

    return render(request, 'main/day.html', context=context)

main/templates/main/day.html
<h1>druglord</h1>
<table>
 <tr>
   <th>Name</th>
   <th>Quantity</th>
   <th>Price</th>
 </tr>

 {% for prod in day.product_set.all %}
 <tr>

   <td>{{ prod.name }}</td>
   <td>{{ prod.quantity }}</td>
   <td>{{ prod.price }}</td>
 </tr>

 {% endfor %}


<a href="{% url 'game-day' char.id next_day %}">Next Day</a>
</table>

main/templates/main/home.html
<h1>druglord</h1>
<table>
 <tr>
   <th>Name</th>
   <th>Cash</th>
   <th>Day</th>
 </tr>

 {% for char in characters %}
 <tr>

   <td><a href="{% url 'game-day' char.id char.on_day.day_number%}"> {{ char.name }}</a></td>
   <td>{{ char.cash }}</td>
   <td>{{ char.on_day.day_number }}</td>
 </tr>

 {% endfor %}

</table>